const InsightCard = () => {
  return (
    <div className="rounded-xl border bg-white p-4 shadow-sm">

      <h3 className="font-semibold mb-3">
        AI Insights
      </h3>

      <p className="text-sm text-slate-500">
        Insights generated by the AI agent will appear here after
        querying the database.
      </p>

    </div>
  );
};

export default InsightCard;